# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='childcidname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
