# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AXF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=100)),
                ('live_time', models.IntegerField()),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AXF.User')),
            ],
            options={
                'db_table': 'u_cookies',
            },
        ),
    ]
