# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180508_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXF.User'),
        ),
    ]
